// 12 new ad groups (numbered 04–15) — true longevity terms based on the
// longevitylifeacademy.com site (consumer cohort course, 8–15 students,
// 18 weeks, 4 phases, six pillars, 600+ Trustpilot reviews, 400k+ students).
// Each ad group has a Desktop and a Mobile mockup.
module.exports = [
  {
    n: '04', name: 'Longevity Protocol',
    nameLines: ['Longevity', 'Protocol'],
    query: 'get your longevity protocol',
    match: 'Phrase',
    domainShown: 'https://www.longevitylifeacademy.com/protocol',
    headline: 'Get Your Personal Longevity Protocol — Built From Your Biomarkers',
    desc: 'A longevity-grade lab panel, two CGM cycles, and a 90-day execution plan — built around your ApoB, Lp(a), VO2 max, and sleep architecture. Cohorts capped at 15. 600+ verified Trustpilot reviews.',
    descShort: 'Longevity-grade labs, 2 CGM cycles, and a 90-day plan built around your ApoB, VO2 max, and sleep.',
    sitelinks: [
      { t: 'Apply for the Next Cohort', d: 'Limited seats. Cohorts cap at 15 students. Apply now.' },
      { t: 'Take the 2-Minute Quiz', d: 'See which biomarkers and protocols matter most for you.' },
      { t: 'See the Curriculum', d: '4 phases. 18 live sessions. Six pillars of healthspan.' },
      { t: 'Read Our Story', d: '25 years online education · 400k+ students · 197 countries.' },
    ],
    competitor: { name: 'Peter Attia MD', host: 'https://peterattiamd.com › framework', heading: 'The Centenarian Decathlon: A Framework for Longevity', snippet: 'A working framework for thinking about exercise, nutrition, sleep, and emotional health as inputs to a longer healthspan…' },
    counts: { results: '12,400,000', secs: '0.38' },
    tabs: ['All','News','Videos','Books','Forums','Images','More'],
  },
  {
    n: '05', name: 'Best Longevity Course',
    nameLines: ['Best Longevity', 'Course'],
    query: 'best longevity course online',
    match: 'Phrase',
    domainShown: 'https://www.longevitylifeacademy.com/course',
    headline: 'The Best Online Longevity Course — Live Cohorts, Real Biomarkers',
    desc: '18 live sessions across nutrition, sleep, exercise, supplements, stress, and your personal protocol. Small cohorts of 8–15. 4.6 ★ on Trustpilot from 600+ verified students.',
    descShort: '18 live sessions across nutrition, sleep, exercise, supplements, stress, and protocol-building.',
    sitelinks: [
      { t: 'Inside the Curriculum', d: '4 phases. 50-minute flows. 90-minute live sessions.' },
      { t: 'Apply for the Next Cohort', d: '8–15 students. 18 weeks. Cohort starts soon.' },
      { t: 'Take the 2-Minute Quiz', d: 'Find out where to start on your longevity journey.' },
      { t: 'Tuition & Payment Plans', d: 'Flexible monthly options. HSA/FSA receipts available.' },
    ],
    competitor: { name: 'Coursera', host: 'https://www.coursera.org › longevity', heading: 'Longevity Science Specialization — 5 Course Series', snippet: 'Learn the biology of aging, evidence-based interventions, and how to translate research into longer healthspan…' },
    counts: { results: '8,930,000', secs: '0.41' },
    tabs: ['All','Images','Videos','News','Shopping','Forums','More'],
  },
  {
    n: '06', name: 'Learn Longevity',
    nameLines: ['Learn', 'Longevity'],
    query: 'learning longevity from experts',
    match: 'Broad',
    domainShown: 'https://www.longevitylifeacademy.com/learn',
    headline: 'Learn Longevity From Practicing Experts — 18-Week Live Cohort',
    desc: 'No medical background required. Plain-English lessons on Medicine 3.0, lifespan vs healthspan, the hallmarks of aging, and how to read your own body data — taught live by longevity practitioners.',
    descShort: 'No medical background needed. Medicine 3.0, the hallmarks of aging, and how to read your body data.',
    sitelinks: [
      { t: 'Phase 1: Foundation', d: 'Aging as modifiable trajectory. Lifespan vs healthspan.' },
      { t: 'Free Sample Lesson', d: 'Watch a 50-minute flow on the four longevity domains.' },
      { t: 'Apply for the Next Cohort', d: 'Live faculty. Small group. Personal blueprint by week 18.' },
      { t: 'Take the 2-Minute Quiz', d: 'Find your starting point in the curriculum.' },
    ],
    competitor: { name: 'edX', host: 'https://www.edx.org › longevity', heading: 'Foundations of Longevity & Healthspan', snippet: 'A self-paced introduction to the biology of aging, healthspan, and lifestyle interventions backed by recent research…' },
    counts: { results: '6,210,000', secs: '0.36' },
    tabs: ['All','Videos','News','Books','Forums','Images','More'],
  },
  {
    n: '07', name: 'Glucose Monitoring',
    nameLines: ['Glucose', 'Monitoring'],
    query: 'continuous glucose monitor non diabetic',
    match: 'Broad',
    domainShown: 'https://www.longevitylifeacademy.com/cgm',
    headline: 'CGM For Non-Diabetics — Read Your Glucose Like A Clinician',
    desc: 'Time-in-range, glucose SD, MAGE, dawn phenomenon — what each metric tells you, what to ignore, and how to translate two weeks of CGM data into a personal nutrition protocol. Free reading guide.',
    descShort: 'Time-in-range, MAGE, dawn phenomenon — what each metric tells you and what to ignore.',
    sitelinks: [
      { t: 'Free CGM Reading Guide', d: 'Time-in-range, MAGE, glucose SD, and dawn phenomenon explained.' },
      { t: 'Phase 2: Data & Discovery', d: 'CGM application, food order, and plate architecture.' },
      { t: 'Apply for the Next Cohort', d: 'Two CGM cycles included with the 18-week curriculum.' },
      { t: 'Take the 2-Minute Quiz', d: 'See if a CGM is the right next step for you.' },
    ],
    competitor: { name: 'Levels Health', host: 'https://www.levelshealth.com › cgm', heading: 'Continuous Glucose Monitoring for Metabolic Health', snippet: 'How non-diabetic CGM users are using glucose data to build personalized nutrition and activity protocols…' },
    counts: { results: '7,260,000', secs: '0.40' },
    tabs: ['All','News','Videos','Forums','Books','Images','More'],
  },
  {
    n: '08', name: 'Track Blood Sugar',
    nameLines: ['Track Blood', 'Sugar'],
    query: 'how to track blood sugar without diabetes',
    match: 'Phrase',
    domainShown: 'https://www.longevitylifeacademy.com/glucose',
    headline: 'Track Your Blood Sugar — Even Without Diabetes',
    desc: 'Fasting glucose, postprandial spikes, overnight curves, and metabolic flexibility — what to measure, how often, and what to change. Build a personal glucose-response framework in two weeks.',
    descShort: 'Fasting glucose, postprandial spikes, and metabolic flexibility — what to measure and what to change.',
    sitelinks: [
      { t: 'Build Your Glucose Frame', d: 'Personal response to meals, sleep, stress, and movement.' },
      { t: 'Post-Meal Walk Protocol', d: 'A 12-minute habit that flattens the postprandial curve.' },
      { t: 'Apply for the Next Cohort', d: '18 weeks. Live faculty. CGM cycles included.' },
      { t: 'Take the 2-Minute Quiz', d: 'See where your metabolic health stands.' },
    ],
    competitor: { name: 'Stanford Medicine', host: 'https://med.stanford.edu › glucose', heading: 'Glucose Variability in Non-Diabetic Adults', snippet: 'A landmark CGM study showing that even non-diabetic adults experience meaningful postprandial spikes that may matter long-term…' },
    counts: { results: '4,380,000', secs: '0.42' },
    tabs: ['All','News','Videos','Forums','Images','Books','More'],
  },
  {
    n: '09', name: 'Brain Fitness',
    nameLines: ['Brain', 'Fitness'],
    query: 'brain fitness training cognitive aging',
    match: 'Broad',
    domainShown: 'https://www.longevitylifeacademy.com/brain',
    headline: 'Brain Fitness — Train The Levers That Actually Matter',
    desc: 'Hippocampal volume, vascular health, ApoB, deep and REM sleep, deliberate novelty. The four lifestyle levers with the strongest evidence — and the protocol we teach inside our cognitive-aging module.',
    descShort: 'ApoB, deep sleep, Zone 2, deliberate novelty — the four levers with the strongest cognitive evidence.',
    sitelinks: [
      { t: 'Cognitive Aging Module', d: 'Memory density, vascular protection, and sleep architecture.' },
      { t: 'Free Brain-Training Guide', d: 'A 7-day protocol pairing novelty with Zone 2 cardio.' },
      { t: 'Apply for the Next Cohort', d: 'Live coaching, biomarker reads, and a personal blueprint.' },
      { t: 'Take the 2-Minute Quiz', d: 'See what is dragging your cognitive baseline.' },
    ],
    competitor: { name: 'Harvard Health', host: 'https://www.health.harvard.edu › brain', heading: 'Lifestyle Strategies to Slow Cognitive Aging', snippet: 'A review of the lifestyle interventions with the strongest evidence for protecting cognition into the seventh and eighth decade…' },
    counts: { results: '11,500,000', secs: '0.39' },
    tabs: ['All','News','Videos','Books','Forums','Images','More'],
  },
  {
    n: '10', name: 'Biohacking Basics',
    nameLines: ['Biohacking', 'Basics'],
    query: 'evidence based biohacking for longevity',
    match: 'Broad',
    domainShown: 'https://www.longevitylifeacademy.com/biohacks',
    headline: 'Evidence-Based Biohacking — No Hype, No Supplement Pitch',
    desc: 'Cold exposure, breathwork, vagal tone, time-restricted eating, sauna, light timing — what holds up under RCTs, what does not, and how to layer the basics before chasing the latest protocol.',
    descShort: 'Cold, breathwork, TRE, sauna, light timing — what holds up under RCTs and what does not.',
    sitelinks: [
      { t: 'The Six Pillars Framework', d: 'Nutrition, sleep, exercise, supplements, stress, protocol.' },
      { t: 'Free Biohacks Tier List', d: 'Foundational, supportive, and experimental — ranked by RCT data.' },
      { t: 'Apply for the Next Cohort', d: 'Build the basics first. Then layer protocols by data.' },
      { t: 'Take the 2-Minute Quiz', d: 'See which biohacks are worth your time right now.' },
    ],
    competitor: { name: 'Andrew Huberman', host: 'https://hubermanlab.com › toolkit', heading: 'The Foundational Fitness & Sleep Toolkit', snippet: 'A practical framework drawn from peer-reviewed studies on sleep, training, and recovery for everyday performance and healthspan…' },
    counts: { results: '8,640,000', secs: '0.37' },
    tabs: ['All','News','Videos','Forums','Books','Images','More'],
  },
  {
    n: '11', name: 'NMN & NAD+',
    nameLines: ['NMN &', 'NAD+'],
    query: 'nmn supplement longevity benefits',
    match: 'Phrase',
    domainShown: 'https://www.longevitylifeacademy.com/supplements',
    headline: 'NMN & NAD+ — What The Evidence Actually Shows',
    desc: 'NMN, NR, and NAD+ precursors explained without the hype. Where the human-trial evidence is strong, where it is weak, and how to think about dosing alongside lipids, sleep, and Zone 2 cardio.',
    descShort: 'NMN, NR, and NAD+ precursors explained without the hype. Where human evidence is strong and where it is weak.',
    sitelinks: [
      { t: 'Supplements Evidence Hierarchy', d: 'Foundational, supportive, experimental — tiered by RCT data.' },
      { t: 'Phase 4: Supplements Module', d: 'NAD+, omega-3, D3+K2, magnesium, creatine, senolytics.' },
      { t: 'Apply for the Next Cohort', d: 'Build a supplement stack from your own biomarkers.' },
      { t: 'Take the 2-Minute Quiz', d: 'See which supplements actually fit your data.' },
    ],
    competitor: { name: 'Peter Attia MD', host: 'https://peterattiamd.com › nad', heading: 'NAD+ Precursors: A Sober Look at NMN and NR', snippet: 'Reviewing the human and animal evidence for NAD+ precursors, including dose, side effects, and clinical relevance to healthspan…' },
    counts: { results: '5,920,000', secs: '0.38' },
    tabs: ['All','Videos','News','Images','Forums','Books','More'],
  },
  {
    n: '12', name: 'Heart Disease Prevention',
    nameLines: ['Heart Disease', 'Prevention'],
    query: 'how to prevent heart disease apob',
    match: 'Phrase',
    domainShown: 'https://www.longevitylifeacademy.com/heart',
    headline: 'Prevent Heart Disease — Lower ApoB Before Symptoms Build',
    desc: 'Most heart attacks are the final chapter of decades of silent plaque. Learn the levers — ApoB, Lp(a), blood pressure, VO2 max — and when to escalate to your clinician. Free ApoB & Lp(a) action guide.',
    descShort: 'ApoB, Lp(a), blood pressure, VO2 max — the levers that slow silent plaque before symptoms.',
    sitelinks: [
      { t: 'Free ApoB & Lp(a) Guide', d: 'A 14-page PDF on testing, targets, and lifestyle levers.' },
      { t: 'Cardiovascular Pathway', d: 'The full silent-plaque, ApoB, and Lp(a) module.' },
      { t: 'Apply for the Next Cohort', d: 'Build your personal protocol over 18 weeks.' },
      { t: 'Take the 2-Minute Quiz', d: 'Find the cardio biomarkers that matter most for you.' },
    ],
    competitor: { name: 'Cleveland Clinic', host: 'https://my.clevelandclinic.org › apob', heading: 'Apolipoprotein B (ApoB): Test, Levels, Results', snippet: 'What ApoB measures, why it predicts atherosclerotic cardiovascular disease better than LDL-C alone, and how to interpret the result…' },
    counts: { results: '6,810,000', secs: '0.41' },
    tabs: ['All','News','Videos','Forums','Books','Images','More'],
  },
  {
    n: '13', name: 'Zone 2 & VO2 Max',
    nameLines: ['Zone 2 &', 'VO2 Max'],
    query: 'zone 2 training heart rate longevity',
    match: 'Phrase',
    domainShown: 'https://www.longevitylifeacademy.com/zone-2',
    headline: 'Zone 2 Training — The Single Biggest Lever For VO2 Max',
    desc: 'Find your true Zone 2, how much you actually need each week, and why VO2 max is one of the strongest correlates of all-cause mortality. Free heart-rate zone calculator inside.',
    descShort: 'Find your true Zone 2, how much you need weekly, and why VO2 max correlates with all-cause mortality.',
    sitelinks: [
      { t: 'Free Heart-Rate Zone Calc', d: 'Estimate your Zone 2 from age, resting HR, and feel.' },
      { t: 'VO2 Max Without A Lab', d: 'Practical field tests and Apple Watch / Garmin notes.' },
      { t: 'Apply for the Next Cohort', d: 'Live coaching on Zone 2, strength, and VO2 max.' },
      { t: 'Inside the Curriculum', d: 'How exercise & movement is taught across all 4 phases.' },
    ],
    competitor: { name: 'Outside Online', host: 'https://www.outsideonline.com › zone-2', heading: 'Why Every Endurance Plan Now Talks About Zone 2', snippet: 'A look at why elite coaches and longevity physicians have converged on the same easy, sustainable training intensity…' },
    counts: { results: '9,540,000', secs: '0.36' },
    tabs: ['All','Videos','News','Forums','Images','Books','More'],
  },
  {
    n: '14', name: 'Longevity Nutrition',
    nameLines: ['Longevity', 'Nutrition'],
    query: 'longevity nutrition plan healthspan',
    match: 'Phrase',
    domainShown: 'https://www.longevitylifeacademy.com/nutrition',
    headline: 'Longevity Nutrition — Eat For Healthspan, Not Hype',
    desc: 'Protein-fiber-processing, food order, plate architecture, 30 plants per week, and time-restricted eating. The framework that flattens glucose and lowers ApoB without a fad diet.',
    descShort: 'Protein-fiber-processing, food order, plate architecture, and 30 plants per week. No fad diet.',
    sitelinks: [
      { t: 'Free Plate Architecture Guide', d: 'A one-pager on assembling longevity-aligned meals.' },
      { t: 'Phase 3: Lifestyle Systems', d: 'Microbiome, fiber, fermentation, short-chain fatty acids.' },
      { t: 'Apply for the Next Cohort', d: 'Live nutrition coaching with biomarker feedback.' },
      { t: 'Take the 2-Minute Quiz', d: 'Find where your nutrition is leaking healthspan.' },
    ],
    competitor: { name: 'Harvard T.H. Chan', host: 'https://www.hsph.harvard.edu › nutrition', heading: 'The Mediterranean Pattern and Healthspan', snippet: 'A summary of cohort and trial evidence linking the Mediterranean dietary pattern with cardiovascular, cognitive, and metabolic outcomes…' },
    counts: { results: '13,700,000', secs: '0.34' },
    tabs: ['All','Images','Videos','News','Books','Forums','More'],
  },
  {
    n: '15', name: 'Rapamycin Protocol',
    nameLines: ['Rapamycin', 'Protocol'],
    query: 'rapamycin for longevity dosage',
    match: 'Phrase',
    domainShown: 'https://www.longevitylifeacademy.com/rapamycin',
    headline: 'Rapamycin For Longevity — A Practical, Evidence-Led Primer',
    desc: 'mTOR, weekly pulse dosing, common side effects, and why most clinicians still call it experimental. A clear-eyed walkthrough for adults considering the conversation with their physician.',
    descShort: 'mTOR, weekly pulse dosing, side effects, and why most clinicians still call it experimental.',
    sitelinks: [
      { t: 'Is Rapamycin Right For You?', d: 'A decision framework — biomarkers, age, risk, and goals.' },
      { t: 'Talk With Your Clinician', d: 'A one-page brief you can bring to your next appointment.' },
      { t: 'Phase 4: Supplements & Therapies', d: 'Rapamycin, metformin, and senolytics taught in cohort.' },
      { t: 'Apply for the Next Cohort', d: 'Build your personal longevity blueprint over 18 weeks.' },
    ],
    competitor: { name: 'Lifespan.io', host: 'https://www.lifespan.io › rapamycin', heading: 'Rapamycin and Longevity: What the Trials Show', snippet: 'A non-commercial overview of rapamycin pharmacology, off-label use, and the current state of human longevity trials…' },
    counts: { results: '4,920,000', secs: '0.44' },
    tabs: ['All','News','Videos','Forums','Books','Images','More'],
  },
];
